### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by nolt** [brunonova/nautilus-admin#13]
Hi,

I just translated nautilus-admin to Polish language. File attached.

Best regards,
Nolt
[po-pl.zip](https://github.com/brunonova/nautilus-admin/files/368646/po-pl.zip)

**Comment by brunonova** [comment]
Thank you! I've commited your translation to the repository.

Could you also translate the file `polkit/org.freedesktop.nautilus-admin.policy`?

**Comment by nolt** [comment]
Sure, file has been translated. I made a pull request already.
Thanks for commit.
