### ISSUE TITLE
 Markup parsing error in Italian translation

### ISSUE THREAD

**Issue by ronnystandtke** [brunonova/nautilus-admin#26]
The Italian translation doesn't close a "\<b\>" element. Therefore the warning message is not shown in the warning dialog but the following error message on the console:

> (nautilus:3016): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Errore alla riga 3 carattere 79: È stato chiuso l'elemento "markup", ma l'elemento correntemente aperto è "b"

The attached patch fixes this issue.
[it.po.txt](https://github.com/brunonova/nautilus-admin/files/644445/it.po.txt)

**Comment by brunonova** [comment]
I have just committed your 3 patches. Thanks a lot for them!

I'll release a new version in the near future.
