### ISSUE TITLE
Doesn't work with Nautilus 3.24

### ISSUE THREAD

**Issue by ceyhunn** [brunonova/nautilus-admin#27]

**Comment by brunonova** [comment]
I just tried it with the current daily live ISO of Ubuntu 17.10 with Nautilus 3.14.1, and it worked fine.

Have you restarted Nautilus after installing the extension? (`nautilus -q`)

**Comment by ceyhunn** [comment]
Sorry for that, I had to give more info. With gnome-xorg, it is OK. Problem with  Gnome Wayland, it gives following error:

> Can not open display :0

**Comment by brunonova** [comment]
Oh, Wayland. I never used Wayland, so I know little about it.

[Apparently it isn't possible to run graphical applications under a different user (like root) under Wayland][1]:

> This is caused by Wayland not allowing processes run as a different user
> to display on the desktop.  Therefore using "su" or "sudo" to display a
> graphical application doesn't work.

So I guess this extension simply can't work under Wayland!
I'll close this bug, since I don't think it can't be fixed.

But I think Nautilus (and Gedit) now have some support to do some tasks as root, so this extension may no longer be needed in the future.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1370324#c3 "Bug 1370324 – gparted cannot open display: :0"

**Comment by ceyhunn** [comment]
I understood. Thanks for your answer!!

**Comment by brunonova** [comment]
And thank you for reporting this!

**Comment by ceyhunn** [comment]
Hi @brunonova ,
I make  your extension work on Gnome-Wayland. Adding environment variable XDG_RUNTIME_DIR of current user like
```
pkexec   env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR nautilus
pkexec   env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR gedit

```
 solves the problem. That's why I did some changes in nautilus-admin.py for nautilus and gedit:
```
 cmd = [PKEXEC_PATH]
 cmd +=['env','XDG_RUNTIME_DIR='+os.environ['XDG_RUNTIME_DIR']]
 cmd +=[NAUTILUS_PATH]
 cmd +=['--no-desktop',uri]
 subprocess.Popen(cmd)
 #subprocess.Popen([PKEXEC_PATH, NAUTILUS_PATH, "--no-desktop", uri])

```

```
 cmd = [PKEXEC_PATH]
 cmd +=['env','XDG_RUNTIME_DIR='+os.environ['XDG_RUNTIME_DIR']]
 cmd +=[GEDIT_PATH]
 cmd +=[uri]
 subprocess.Popen(cmd)
 #subprocess.Popen([PKEXEC_PATH, GEDIT_PATH, uri])
```

**Comment by brunonova** [comment]
Thanks!
I have added your changes to the extension.

I can't really test it now, so I'll take your word for it that it works.

**Comment by ceyhunn** [comment]
@brunonova,  but there are some tiny problems in org.freedesktop.nautilus-admin.policy  like pkexec messages.  I don't know them very well.

**Comment by brunonova** [comment]
What messages are you referring to?

**Comment by ceyhunn** [comment]
@brunonova ,
Example:  Your Nautilus Message - Authentication is required to run the File Manager as Administrator  like this -  Authentication is needed to run /usr/bin/env  as the superuser.

**Comment by brunonova** [comment]
Oh, right! `pkexec` is now running `env` instead of `nautilus`, so the policykit file no longer applies.
I'll take a look at this tomorrow.

**Comment by brunonova** [comment]
I don't think there's another way to preserve environment variables with polkit besides using that `env` trick, but then the policykit file no longer applies.
I have reverted the change.

Try running:

    xhost +local:
    pkexec nautilus --no-desktop

To see if this works to open Nautilus as root under Wayland.
You can also try the other workarounds mentioned in:
* https://ask.fedoraproject.org/en/question/101641/run-gedit-as-root-in-wayland/
* https://bugzilla.redhat.com/show_bug.cgi?id=1274451
