### ISSUE TITLE
Use gvfs admin backend instead of pkexec

### ISSUE THREAD

**Issue by jbicha** [brunonova/nautilus-admin#29]
gvfs 1.30 (generally included in GNOME 3.22 distros) has a new admin backend.

Instead of running an app as root or using pkexec, you can just use the `admin://` prefix.

For instance, to edit your grub settiings, you can open `admin:///etc/default/grub` in gedit

To browse the root home directory, just navigate to `admin:///root/`

That takes care of Open and Edit as Administrator which I assume would be the most common features of this extension.

The admin backend is useful because GNOME on Wayland currently does not support pkexec. This issue is a follow up for https://github.com/brunonova/nautilus-admin/issues/27

**Comment by brunonova** [comment]
I've been a bit out of the loop lately.
I didn't know about that new admin backend. That's awesome!

Yes, that's a good idea. Thanks!

**Comment by brunonova** [comment]
Done! I tested it on the latest Fedora version and it seems to work fine.
I'll release a new version now.
