### ISSUE TITLE
Nautilus 3.26 missing the context menu item

### ISSUE THREAD

**Issue by webmastak** [brunonova/nautilus-admin#32]
OS: Manjaro 17.0.6 Gellivara
Kernel: x86_64 Linux 4.9.60-1-MANJARO
Shell: bash
DE: GNOME 
WM: GNOME Shell

Open as Administrator: opens a folder:
missing the context menu item - "Delete"
https://i.imgur.com/Kq8UoR4.png

I'm saving myself with a crutch:
.local/share/nautilus/scripts/Admin

```
#!/bin/bash
gksu nautilus $NAUTILUS_SCRIPT_SELECTED_URIS
```

**Comment by brunonova** [comment]
If you're using version 1.0.0 or greater of the extension, then this is a bug in Nautilus itself. You should report this bug there.
The extension now makes use of the new "admin" backend in Nautilus, by opening a new window in a location like `admin:///usr/share/nautilus-python/extensions`, which is something that you can do yourself without any extensions.

**Comment by webmastak** [comment]
https://i.imgur.com/Kq8UoR4.png 
this window is open through: admin:///usr/share/nautilus-python/extensions 
and through: Open as Administrator

missing the context menu item - "Delete"
inactive the context menu item - "Сut"
inactive the context menu item - "Rename"

**Comment by brunonova** [comment]
You should report this problem to the developers of Nautilus. There's nothing I can do from my side.

Now, you could use an older version of the extension (older than 1.0.0). In the older versions, the extension would actually run Nautilus as root (similar to your script), but it doesn't work under Wayland.

**Comment by webmastak** [comment]
thanks, this works well: https://aur.archlinux.org/packages/nautilus-admin
