### ISSUE TITLE
Modificação do lang_pt.properties para Português (Brasil)

### ISSUE THREAD

**Issue by crcpucmg** [brunonova/nautilus-admin#33]
Olá,

Solicitamos a gentileza de incluir o ficheiro/anexo e habilitá-lo na seleção de idioma
 
[lang_ptbr.zip](https://github.com/brunonova/nautilus-admin/files/1555690/lang_ptbr.zip)

Atenciosamente

Pontifícia Universidade Católica de Minas Gerais - Brasil
Centro de Recursos Computacionais

**Comment by brunonova** [comment]
Penso que esta issue se refere ao projeto https://github.com/brunonova/drmips.
