### ISSUE TITLE
Not working with Python3 in Arch

### ISSUE THREAD

**Issue by vageliskatsiotis** [brunonova/nautilus-admin#35]
Using python-nautilus( pointing to python3 and not python2-nautilus) the menu item does not appear.

Running `python nautilus-admin.py` from `/usr/share/nautilus-python/extensions/` I get the message

**nautilus-admin.py:19: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Nautilus, GObject**

Adding those lines into `python nautilus-admin.py` adds double entry in the nautilus menu(both working)

**Comment by cbowman57** [comment]
Just to confirm, using python2-nautilus works but does result in the double entries in the menu.
  
EDIT: Reasonably certain this bug was introduced with the changes to python-nautilus and/or python2-nautilus packages in Arch

**Comment by zgwerby** [comment]
All python(2) nautilus extensions not working. I just seen this on open-tilix.py


I have been added now pull request with fix. But "Duplicate menu entry"-bug mainstream(?) bug

**Comment by brunonova** [comment]
The pull request (#37) has been merged.

I don't have an Arch system. Could someone confirm that this fixes the issue of the extension not working?

**Comment by zgwerby** [comment]
For me - working fine, waiting for other users reaction.
Duplicate menu entry'll be fixed in next release of python-nautilus, [@bil-elmoussaoui](https://github.com/gnunn1/tilix/issues/1250#issuecomment-356675742)

**Comment by vageliskatsiotis** [comment]
I'll check it later today and get back to you. Working on antergos.

**Comment by infirit** [comment]
That gi warning has nothing to do with a python version. And it is just a warning that does not prevent the execution of the extension.

The warning means that you are not explicit which version of the library your code relies on. If a new version comes out that is incompatible your module may stop working properly. 

It is good to be explicit here but it in no way can solve the problems described here.

Also urllib was imported in an earlier, pre gvfs admin backend, version which likely is the current version available for arch users.

**Comment by brunonova** [comment]
Indeed. The AUR package is on version 0.2.5, while the extension here is on version 1.1.2.

**Comment by vageliskatsiotis** [comment]
Duplicate entry gone, but after I get the prompt for sudo password, nautilus opens as "some" user(not my user because locks appear on the folders as shown in the screenshot) and not as root. 
![screenshot from 2018-01-11 22-38-48](https://user-images.githubusercontent.com/7825498/34846266-42a6908a-f720-11e7-9ae0-ebe2a5c1a2cf.png)

**Comment by brunonova** [comment]
Hmm... the folders have locks, but I can see in that screenshot that the /root folder has a "home" icon, as if it's the home folder.
Could you check if, after opening "/" as admin, you can access `/root` or if you can open `/etc/shadow` in the text editor from there? Usually only root can access those.

Oh, and by the way, the extension no longer opens a new Nautilus window as the root user, as that doesn't work under Wayland.
Instead, it uses Nautilus' admin backend by opening the folder/file in a new Nautilus window as a normal user with a special URL.
Press Ctrl+L to see the full location path. If it starts with `admin://`, then you have that folder open as an administrator.

**Comment by vageliskatsiotis** [comment]
root folder opens successfully and /etc/shadow also after requesting one more time for the sudo password. But I  cannot delete or rename folders and files. It's greyed out. With the previous versions a new root nautilus opened with root as home.

**Comment by brunonova** [comment]
I can see the same behavior that you describe in Ubuntu: I cannot delete or rename files in /root, but I can create new files and folders and delete or rename those.

Unfortunately, I can't do anything about that. That's a bug in the admin backend of Nautilus or gvfs (or maybe it's a design decision).

If you prefer the old behavior of the extension, where it would actually open a Nautilus window as root, you can you the [older 0.2.5 version](https://github.com/brunonova/nautilus-admin/releases/tag/v0.2.5).
It won't work with Wayland, though.

I'm going to release a new version with zgwerby's pull request.

**Comment by brunonova** [comment]
Version released. I don't think I can do anything more from my side, so I'm closing this issue.

Thank you all!
