### ISSUE TITLE
Doesn't open folders / files owned by root in CentOS 7

### ISSUE THREAD

**Issue by Spork-Schivago** [brunonova/nautilus-admin#38]
I'm running CentOS 7 with gvfs.x86_64 version 1.30.4, release 3.el7, however, the admin:///<filepath> does not work for me, and this extension is not working either (I'm assuming that because admin:///<filepath> does not work, this extension won't work).

I can successfully compile the extension and install it, and when I do, I do see an Open as Administrator / Edit as Administrator right-click option in Nautilus, but when I right-click on a directory owned by root, and select Open as Administrator, it opens a new blank window, and then after a period of time, that blank window just closes.

The title in the task bar at the bottom of my screen shows Loading... for that window.

If I try to edit a file, I see gedit in the bottom taskbar, however, after a short bit, I'm prompted with a message saying GEdit timed out and I can kill it or wait.   If I pick wait, eventually, it'll pop open, displaying the message:

Could not open the file "admin:///home/spork/Desk...p/Root%20Terminal.desktop".
Connection timed out.   Please try again.

It seems to be related to the gvfs admin backend not working as expected in CentOS 7.   If I run:

rpm -ql gvfs.x86_64

I see the following files are provided by that installed package:
/usr/lib/systemd/user/gvfs-daemon.service
/usr/lib/systemd/user/gvfs-metadata.service
/usr/lib/systemd/user/gvfs-udisks2-volume-monitor.service
/usr/lib64/gvfs/libgvfsdaemon.so
/usr/libexec/gvfs-udisks2-volume-monitor
/usr/libexec/gvfsd
/usr/libexec/gvfsd-admin
/usr/libexec/gvfsd-burn
/usr/libexec/gvfsd-cdda
/usr/libexec/gvfsd-computer
/usr/libexec/gvfsd-dav
/usr/libexec/gvfsd-dnssd
/usr/libexec/gvfsd-ftp
/usr/libexec/gvfsd-http
/usr/libexec/gvfsd-localtest
/usr/libexec/gvfsd-metadata
/usr/libexec/gvfsd-network
/usr/libexec/gvfsd-recent
/usr/libexec/gvfsd-sftp
/usr/libexec/gvfsd-trash
/usr/share/GConf/gsettings/gvfs-dns-sd.convert
/usr/share/GConf/gsettings/gvfs-smb.convert
/usr/share/dbus-1/services/org.gtk.vfs.Daemon.service
/usr/share/dbus-1/services/org.gtk.vfs.Metadata.service
/usr/share/dbus-1/services/org.gtk.vfs.UDisks2VolumeMonitor.service
/usr/share/glib-2.0/schemas/org.gnome.system.dns_sd.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.system.gvfs.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.system.smb.gschema.xml
/usr/share/gvfs
/usr/share/gvfs/mounts
/usr/share/gvfs/mounts/admin.mount
/usr/share/gvfs/mounts/burn.mount
/usr/share/gvfs/mounts/cdda.mount
/usr/share/gvfs/mounts/computer.mount
/usr/share/gvfs/mounts/dav+sd.mount
/usr/share/gvfs/mounts/dav.mount
/usr/share/gvfs/mounts/dns-sd.mount
/usr/share/gvfs/mounts/ftp.mount
/usr/share/gvfs/mounts/ftps.mount
/usr/share/gvfs/mounts/http.mount
/usr/share/gvfs/mounts/localtest.mount
/usr/share/gvfs/mounts/network.mount
/usr/share/gvfs/mounts/recent.mount
/usr/share/gvfs/mounts/sftp.mount
/usr/share/gvfs/mounts/trash.mount
/usr/share/gvfs/remote-volume-monitors
/usr/share/gvfs/remote-volume-monitors/udisks2.monitor
/usr/share/man/man1/gvfsd-metadata.1.gz
/usr/share/man/man1/gvfsd.1.gz
/usr/share/polkit-1/actions/org.gtk.vfs.file-operations.policy
/usr/share/polkit-1/rules.d/org.gtk.vfs.file-operations.rules

I would think /usr/libexec/gvfsd-admin would be the gvfs admin backend.    Any suggestions on why this doesn't work for me or how to fix it?   It's a fresh install of CentOS 7.4.1708.

Thanks!

**Comment by brunonova** [comment]
So, even typing "admin:///" in the location bar of Nautilus doesn't work?

Try rebooting if you haven't already. Then ask around in the CentOS forums.
I can't be of much help here.

**Comment by Spork-Schivago** [comment]
The admin:/// does not work, but I found a way to get your plugin working.   I'm thinking this plugin might not work on any CentOS distribution.   This is what I had to do.   First, I had to find the DBUS session address, which wasn't hard.   I'm logged in as spork, and it's exported as DBUS_SESSION_BUS_ADDRESS.

So, running:
export |grep DBUS_SESSION_BUS_ADDRESS

gives me:

declare -x DBUS_SESSION_BUS_ADDRESS="unix:abstract=/tmp/dbus-J2bNTl2MbU,guid=8bccbd9e7a32f35ece98fb2e5a7cc9ab"

Then I had to manually start gvfsd-admin as spork.   I did this by running:
pkexec /usr/libexec/gvfsd-admin --address unix:abstract=/tmp/dbus-J2bNTl2MbU

Afterwards, I verified the gvfsd-admin process was running using ps aux, which showed it was.    Then, your plugin worked.

I have a few friends running CentOS 7, with fresh installs, but a little different security configuration than mine, and we can try on theirs.

I'm wondering if gvfsd-admin is running on other systems or if it's only running when needed.   I'd think gvfsd would start the gvfsd-admin backend when needed....maybe this is a CentOS 7 bug?

**Comment by brunonova** [comment]
Yes, maybe it's a bug.
Report it, or ask around in their forums.

**Comment by Spork-Schivago** [comment]
I might just modify your extension a bit for myself, to check if gvfsd-admin is running, if not, have pkexec execute it, with the address to the DBUS session.   That will fix the problem for me at least.   Might not be a bad idea to have your code check if gvfsd-admin is running anyways, and if not, execute it....just a thought.

**EDIT:  I've asked in the forums to see what they say.   I'll keep ya updated if I get a response.   I noticed even gio list admin:///root   (or /boot/grub2 in my case) fails as well, unless gvfsd-admin is manually started.   So I think this might be a bug in gvfsd not starting gvfsd-admin when it's supposed to.

**Comment by brunonova** [comment]
Thanks!

**Comment by Spork-Schivago** [comment]
This is now a confirmed bug in RedHat / CentOS:

https://bugzilla.gnome.org/show_bug.cgi?id=793445

The second patch fixes it I believe, but I'll probably have to wait until it makes it's way down-stream.

Thanks.   I think we can close this issue now, because it's not related to the plugin, but a problem with pkexec and how it spawns processes on certain distros.

Thanks!

**Comment by brunonova** [comment]
Great! Thanks for your investigation!
