### ISSUE TITLE
unknown option --no-desktop

### ISSUE THREAD

**Issue by killajoe** [brunonova/nautilus-admin#40]
Just after upgrade to GNOME 3.28 i get this error and n-a do not work:

`org.gnome.Nautilus[524]: unknown option --no-desktop`

from .py

`def _nautilus_run(self, menu, file):
		"""'Open as Administrator' menu item callback."""
		uri = file.get_uri()
		admin_uri = uri.replace("file://", "admin://")
		subprocess.Popen([NAUTILUS_PATH, "--no-desktop", admin_uri])`

Same on Archlinux + Antergos

**Comment by kouros17** [comment]
The same issue in manjaro (nautilus 3.28). It seems that nautilus-admin doesn’t work with folders, only with text files. When right click on folders and “open as Administrator” I get:

> unknown option --no-desktop

but on text files works without issues.

**Comment by brunonova** [comment]
GNOME has recently dropped support for the desktop in Nautilus, right? That's probably it.

I'll remove that argument.

**Comment by brunonova** [comment]
I just released [a new version][1]. That should fix this issue.

[1]: https://github.com/brunonova/nautilus-admin/releases/tag/v1.1.5

**Comment by kouros17** [comment]
@brunonova thanks a lot. It’s fixed in 1.1.5. :+1:

**Comment by killajoe** [comment]
thanks!
