### ISSUE TITLE
Untagged v1.1.7

### ISSUE THREAD

**Issue by e7appew** [brunonova/nautilus-admin#44]
Not really an issue with the project itself, but something about how version 1.1.7 was released is causing my non-standard Debian watch file to fail. If you have a look at https://github.com/brunonova/nautilus-admin/releases, you'll see that the files are stored under https://github.com/brunonova/nautilus-admin/releases/download/untagged-3dea55396abd97dc4150/ instead of https://github.com/brunonova/nautilus-admin/releases/download/v1.1.7/, and it doesn't say that the release is verified even though the tar archive is signed.

**Comment by brunonova** [comment]
Sorry, not sure what happened. It should be correct now.
