### ISSUE TITLE
nautilus-admin old way

### ISSUE THREAD

**Issue by mfauvain** [brunonova/nautilus-admin#47]
Hi, trying to use the old (and great!) nautilus admin in gnome 3.28 (and Arch) to get rid of the bug with admin backend. Compiled version 0.2.5 as you mentioned in a closed issue, however menu doesn't show up in Nautilus. Checked polkit files and python extension but cant tell what's wrong. Anything obvious I am missing? I understand 0.2.5 is an older version but any help here much appreciated.

EDIT : not to worry, I've modified the py scripts from v1.1.7 to go back to pkexec method. Can close issue. thx for v useful extension.

**Comment by brunonova** [comment]
Great!
