### ISSUE TITLE
Fedora python-nautilus refers to python2-nautilus, which breaks python nautilus extensions.

### ISSUE THREAD

**Issue by JochemKuijpers** [brunonova/nautilus-admin#48]
Installing nautilus-admin through the released package, following the instructions in [INSTALL.md](https://github.com/brunonova/nautilus-admin/blob/master/INSTALL.md), the following error occurs when running `nautilus -q` to finish installation:

```
$ nautilus -q

(nautilus:9442): Nautilus-Python-WARNING **: 15:36:29.532: g_module_open libpython failed: /usr/lib64/libpython3.7.so.1.0: cannot open shared object file: No such file or directory
ImportError: could not import gobject (error was: ImportError('/usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError'))

(nautilus:9442): Nautilus-Python-WARNING **: 15:36:29.579: pygobject initialization failed

(nautilus:9442): Nautilus-Python-WARNING **: 15:36:29.579: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-admin.py", line 20, in <module>
    from gi import require_version
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
```

I found [this related discussion](https://bugzilla.redhat.com/show_bug.cgi?id=1636626) on the Red Hat bugzilla. Installing `python-nautilus` actually installs a package named `python2-nautilus`. The linked discussion and the missing python3 errors led me to believe I should not depend on python2 but instead on python3.

The solution is to remove `python-nautilus` and instead install `python3-nautilus` as follows.
```
$ sudo dnf remove python-nautilus
$ sudo dnf install python3-nautilus
$ nautilus -q
```
This removes the `python2-nautilus` package and installs the `nautilus-python` package (which lacks the 3 in the package name, to add to the confusion..). Now it works without issue.

Please consider updating `INSTALL.md` to reflect this broken dependency.

For reference, I'm using GNOME nautilus 3.30.3 on a fresh install of Fedora 29.

**Comment by JochemKuijpers** [comment]
To quote some relevant sections of the Red Hat discussion ([again, link here](https://bugzilla.redhat.com/show_bug.cgi?id=1636626))

> Raphael, are you ok with me going ahead and fixing this? There are a few things going wrong with the packaging here, and I think the root cause is that nautilus-python only supports one Python version at a time (you can't register an extension twice, once with Python 2 and once with Python 3). I think a good plan here is to build nautilus-python against Python 2 in F29 and switch to Python 3 in F30.

--

> I would propose a different route to fix this problem:
If we revert the package as it was in F28, this will break again in F30.
Let's take advantage of this breakage instead, and fix the problem once and for all in the following way:  
>
> As Python2 will be retired in 2020, and nautilus-python can be built against a single Python version, let's build only the Python3 version instead, and repackage all the components that needed python2-nautilus to require python3-nautilus.  
>
> If an extension breaks after this change, it means that the upstream extension should be ported to Python3, but such porting will be necessary in any case due to the Python2 EOL nearing day by day.

--

> ...
> So, I agree, let's rip off the bandage now and just swap python3-nautilus in for python2-nautilus (moving the "Provides: nautilus-python" to the python3-nautilus package in the process). Then it's done and we never have to think about this again. (Until Python 4.) ;-)

I recommend reading the entire discussion, I cannot summarize everything being said there. [It does look like python2 support is being phased out starting just about now.](https://fedoraproject.org/wiki/Changes/NautilusExtensionsPython3) Luckily nautilus-admin works with python3 so it should not require code changes, just a change in install documentation.

The relevant dependency package is called `nautilus-python` (not `python-nautilus`) for Fedora based systems.

**Comment by brunonova** [comment]
The packages listed in `INSTALL.md` are the known dependencies for Ubuntu and Debian.

Still, I updated the file to mention `nautilus-python` for Fedora.
