### ISSUE TITLE
not  working with xrdp centos7

### ISSUE THREAD

**Issue by theoppermann** [brunonova/nautilus-admin#53]
it works when locally connected but over vnc / xrdp i never get the password box

**Comment by theoppermann** [comment]
this is properly related to nautilus admin:/// not working with vnc?

**Comment by brunonova** [comment]
I just tried it over VNC (and Xorg) on Ubuntu, and it worked for me.

But yes, the only thing the extension does is to open the "admin:///" link in Nautilus.
If putting "admin:///" directly in the location bar of Nautilus doesn't work, then it's a problem in Nautilus
