### ISSUE TITLE
Asks for passwd twice

### ISSUE THREAD

**Issue by tad1073-zz** [brunonova/nautilus-admin#54]
As the description says, I have to enter my passwd twice when using this feature.

**Comment by loucurapt** [comment]
What distribution? Ubuntu?

**Comment by tad1073-zz** [comment]
> What distribution? Ubuntu?

Yes Ubuntu 19.04, I believe it also happens on 18.04 as well.

**Comment by loucurapt** [comment]
I've seen this issue occur in Ubuntu.
If you go to the location bar (Ctr+L) in the file manager and enter `admin:///` manually - which is what the extension does - it asks for the password twice.

It's some issue in Ubuntu. You'll have to [report it in Ubuntu](https://help.ubuntu.com/community/ReportingBugs).

**Comment by tad1073-zz** [comment]
> I've seen this issue occur in Ubuntu.
> If you go to the location bar (Ctr+L) in the file manager and enter `admin:///` manually - which is what the extension does - it asks for the password twice.
> 
> It's some issue in Ubuntu. You'll have to [report it in Ubuntu](https://help.ubuntu.com/community/ReportingBugs).

I've been using nautilus admin:// as a test and have only had to enter my passwd once as well as with gedit admin://

**Comment by brunonova** [comment]
Hmm... I had seen this issue in 18.04, and it happened even when going to "admin://" manually in Nautilus.
If "admin://" now only asks for the password once, then I don't know. The only thing the extension does is run "nautilus admin:///path/to/folder".

I don't use Ubuntu anymore, so I can't investigate the issue.
Could someone else check this?

**Comment by tad1073-zz** [comment]
Here's what I did, nautilus admin:///%d

**Comment by brunonova** [comment]
I finally got around to install Ubuntu 19.04 in a virtual machine and, the first time I access admin:/// after login, I always get 2 password prompts - one for "gvfsd-admin daemon", the other to "perform file operations".
It doesn't matter if I use the extension or if I input "admin:///" into the file manager's location bar.
Same thing for gedit.
